"""Create flash_card table

Revision ID: 19552af4cc65
Revises: 
Create Date: 2024-06-29 00:21:07.673954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19552af4cc65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_word', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flash_card')
    # ### end Alembic commands ###
