"""Add attribute <attempts> in flash_card table

Revision ID: 5de6fd30f53c
Revises: 19552af4cc65
Create Date: 2024-06-29 01:07:20.484979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de6fd30f53c'
down_revision = '19552af4cc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
